### ISSUE TITLE
default keyword for max() added in Python 3.4

### ISSUE THREAD

**Issue by grit96** [itsapi/pycraft#100]
https://docs.python.org/3/library/functions.html#max

```
Traceback (most recent call last):
  File "main.py", line 312, in <module>
    main()
  File "main.py", line 19, in main
    game(blocks, *ui.main())
  File "main.py", line 128, in game
    last_frame
  File "/home/pi/python/pycraft/render.py", line 64, in render_map
    pixel_out = calc_pixel(x, y, pixel, objects, blocks, bk_objects, sky_colour, lights, tick)
  File "/home/pi/python/pycraft/render.py", line 110, in calc_pixel
    bg = sky(x, y, tick, bk_objects, sky_colour, lights)
  File "/home/pi/python/pycraft/render.py", line 190, in sky
    light = max(light_levels, key=lambda l: l[2], default=sky_colour)
TypeError: max() got an unexpected keyword argument
```

**Comment by olls** [comment]
Well what version of Python are we aiming to support?
