### ISSUE TITLE
C-renderer crash on large viewports

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#144]
Once the size of the view gets above around 30x80 it starts to crash after between 0-10 frames with the following error:

```
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 404, in <module>
    main()
  File "main.py", line 43, in main
    game(server_obj, settings, benchmarks)
  File "main.py", line 317, in game
    server.spawn_mobs(n_mob_spawn_cycles, bk_objects, sky_colour, day, lights)
  File "/home/olls/repos/python/pycraft/server_interface.py", line 384, in spawn_mobs
    self._server.local_interface_spawn_mobs(*args)
  File "/home/olls/repos/python/pycraft/server.py", line 216, in local_interface_spawn_mobs
    self.game.spawn_mobs(*args)
  File "/home/olls/repos/python/pycraft/server.py", line 323, in spawn_mobs
    render_interface.create_lighting_buffer(width, height, x_start, y_start, self._map, self._slice_heights, bk_objects, sky_colour, day, lights)
  File "/home/olls/repos/python/pycraft/render_interface.py", line 35, in create_lighting_buffer
    return render_c.create_lighting_buffer(width, height, x, y, map_, slice_heights, bk_objects, sky_colour, day, lights, settings_ref)
SystemError: <built-in function create_lighting_buffer> returned a result with an error set

```

**Comment by grit96** [comment]
I think that was the same crash I was getting
