### ISSUE TITLE
Cursor out of bounds

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#95]
There is an error when the cursor is not on the screen. This can be triggered by falling out of the world with the cursor pointed down.

**Comment by olls** [comment]
```
Traceback (most recent call last):
  File "main.py", line 300, in <module>
    main()
  File "main.py", line 18, in main
    game(blocks, *ui.main())
  File "main.py", line 185, in game
    new_new_slices[tx][ty] = ' '
IndexError: list assignment index out of range
```

**Comment by olls** [comment]
```
Traceback (most recent call last):
  File "main.py", line 273, in <module>
    main()
  File "main.py", line 18, in main
    game(blocks, *ui.main())
  File "main.py", line 109, in game
    x, y, cursor, map_, blocks, meta['inv'], inv_sel
  File "/home/olls/Downloads/repos/python/pycraft/player.py", line 127, in cursor_colour
    block = blocks[ map_[ x + cursor_x[cursor] ][ y + cursor_y[cursor] ] ]
IndexError: list index out of range
```
